title: Marco Antonio 
logo: img/WhatsApp Image 2024-08-21 at 18.32.27-modified.png
description: Estou empenhado em adquirir experiência profissional e colocar em prática os conhecimentos adquiridos ao longo da minha formação acadêmica. Sou uma pessoa dedicada, comprometida e estou disposto a aprender e me desenvolver. Tenho interesse em contribuir para o crescimento da empresa e estou aberto a novos desafios
show_downloads: true 
theme : jekyll-theme-minimal
